#!/usr/bin/env bash
# repro/00_env.sh — shared configuration for TA-OPD 4B→1.7B full reproduction
# Source this file at the top of every repro script:
#   source "$(dirname "${BASH_SOURCE[0]}")/00_env.sh"

set -eo pipefail  # 不能用 -u：conda 内部 deactivate 脚本有 unbound variable

# ── Paths ──────────────────────────────────────────────────────────────────
PROJECT_ROOT="${PROJECT_ROOT:-/inspire/hdd/project/multi-agent/zhangweinan-24046/dk/CacheOPD/taopd_baseline}"
DATA_DIR="${DATA_DIR:-/inspire/hdd/project/multi-agent/zhangweinan-24046/dk/data}"
MODEL_DIR="${MODEL_DIR:-/inspire/hdd/project/multi-agent/zhangweinan-24046/dk/modelweights}"
OUTPUT_ROOT="${OUTPUT_ROOT:-/inspire/hdd/project/multi-agent/zhangweinan-24046/dk/outputs}"

REPO_ROOT="${PROJECT_ROOT}/TA-OPD"
SLIME_DIR="${REPO_ROOT}/slime_ta_opd"
MEGATRON_LM_DIR="${PROJECT_ROOT}/Megatron-LM"
TOOLS_DIR="${REPO_ROOT}/tools"
REPRO_DIR="${REPO_ROOT}/repro"

TEACHER_MODEL="${MODEL_DIR}/Qwen3-4B"
STUDENT_HF="${MODEL_DIR}/Qwen3-1.7B"
STUDENT_TORCH_DIST="${MODEL_DIR}/Qwen3-1.7B_torch_dist"

PROMPT_DATA="${DATA_DIR}/DAPO-Math-17k-dedup/dapo_math_17k_dedup_slime.jsonl"
HELDOUT_DATA="${DATA_DIR}/DAPO-Math-17k-dedup/dapo_math_17k_dedup_slime_heldout300_seed41717.jsonl"
GSM8K_DATA="${DATA_DIR}/GSM8K-COT/gsm8k_cot_slime_300_seed41717.jsonl"

# ── Conda ──────────────────────────────────────────────────────────────────
CONDA_ENV="${CONDA_ENV:-ta_opd}"
CONDA_SH="${CONDA_SH:-$(conda info --base 2>/dev/null || echo "${HOME}/miniconda3")/etc/profile.d/conda.sh}"

# ── HuggingFace mirror (China mainland) ────────────────────────────────────
export HF_ENDPOINT="${HF_ENDPOINT:-https://hf-mirror.com}"

# ── GPU layout (8× RTX 4090 48 GB) ────────────────────────────────────────
# 2 lanes × 3 GPUs each = 6 GPUs used; 2 GPUs spare
#   Lane A: Teacher GPU0, Student GPU1,2 (dp=2, colocate)
#   Lane B: Teacher GPU3, Student GPU4,5 (dp=2, colocate)

LANE_A_TEACHER_GPU=0
LANE_A_STUDENT_GPUS="1,2"
LANE_A_EVAL_GPUS="0,1"

LANE_B_TEACHER_GPU=3
LANE_B_STUDENT_GPUS="4,5"
LANE_B_EVAL_GPUS="3,4"

ACTOR_NUM_GPUS_PER_NODE=2
ROLLOUT_NUM_GPUS=1
COLOCATE=1

# ── Port bases (per-lane offset) ──────────────────────────────────────────
LANE_A_PORT_BASE=0
LANE_B_PORT_BASE=100

# ── Training hyperparameters (paper-exact) ────────────────────────────────
# Main sweep
MAIN_NUM_ROLLOUT=50
MAIN_ROLLOUT_BATCH_SIZE=4
MAIN_N_SAMPLES_PER_PROMPT=2
MAIN_GLOBAL_BATCH_SIZE=8
MAIN_MICRO_BATCH_SIZE=1
MAIN_SAVE_INTERVAL=10
MAIN_ROLLOUT_MAX_RESPONSE_LEN=64
MAIN_ROLLOUT_TEMPERATURE=1.0
MAIN_OPD_TOPK_METRICS_K=16

# Diagnostic
DIAG_NUM_ROLLOUT=151
DIAG_ROLLOUT_BATCH_SIZE=2
DIAG_N_SAMPLES_PER_PROMPT=1
DIAG_GLOBAL_BATCH_SIZE=2
DIAG_MICRO_BATCH_SIZE=1
DIAG_SAVE_INTERVAL=25
DIAG_ROLLOUT_MAX_RESPONSE_LEN=256
DIAG_OPD_TOPK_METRICS_K=16
DIAG_OPD_EXACT_CMASS=1
DIAG_OPD_EXACT_CMASS_MAX_UNION=128

# ── Optimizer / algorithm (paper-exact) ───────────────────────────────────
LR=1e-6
LR_DECAY_STYLE=constant
WEIGHT_DECAY=0.1
ADAM_BETA1=0.9
ADAM_BETA2=0.98
ADVANTAGE_ESTIMATOR=grpo
OPD_KL_COEF=1.0
KL_LOSS_COEF=0.00
KL_LOSS_TYPE=low_var_kl
ENTROPY_COEF=0.00
EPS_CLIP=0.2
EPS_CLIP_HIGH=0.28
OPD_COMPAT_PROXY=mass
OPD_METRIC_NORMALIZATION=batch_quantile
OPD_BUDGET_GAMMA=0.5
OPD_TOKEN_BANK_FORMAT=csv

# ── SGLang settings ──────────────────────────────────────────────────────
TEACHER_MEM_FRACTION=0.55
TEACHER_CUDA_GRAPH_MAX_BS=8
ROLLOUT_MEM_FRACTION=0.45
SGLANG_CUDA_GRAPH_MAX_BS=8

# Diagnostic uses smaller batch → lower mem fractions
DIAG_TEACHER_MEM_FRACTION=0.54
DIAG_TEACHER_CUDA_GRAPH_MAX_BS=2
DIAG_ROLLOUT_MEM_FRACTION=0.22
DIAG_SGLANG_CUDA_GRAPH_MAX_BS=2

# ── Seeds ─────────────────────────────────────────────────────────────────
SEED1_SEED=1234;       SEED1_ROLLOUT_SEED=42;  SEED1_MASK_SEED=42
SEED2_SEED=1235;       SEED2_ROLLOUT_SEED=43;  SEED2_MASK_SEED=43
SEED3_SEED=1236;       SEED3_ROLLOUT_SEED=44;  SEED3_MASK_SEED=44

# Diagnostic seeds
DIAG_HELDOUT_SEED=41717
DIAG_GSM8K_SEED=41731

# Bootstrap analysis seed
BOOTSTRAP_SEED=20260512

# ── All 28 (mask, ratio) combinations ────────────────────────────────────
# Format: mask:ratio  (one per line for easy iteration)
ALL_RUNS=(
  "full:1.0"
  "dlearn_high:0.01"
  "dlearn_high:0.03"
  "dlearn_high:0.05"
  "dlearn_high:0.10"
  "q3_highc:0.01"
  "q3_highc:0.03"
  "q3_highc:0.05"
  "q3_lowc:0.03"
  "dincompat_high:0.03"
  "random:0.03"
  "random:0.05"
  "divergence:0.03"
  "divergence:0.05"
  "tip:0.03"
  "tip:0.05"
  "tip:0.10"
  "ca_softor:0.03"
  "ca_softor:0.05"
  "ca_softor:0.10"
  "q3:0.03"
  "q3:0.05"
  "entropy:0.03"
  "entropy:0.05"
  "entropy:0.10"
  "q3_teachability_high:0.03"
  "q3_teachability_low:0.03"
  "q3_dincompat_high:0.03"
)

# ── Shared context bank / baseline (generated by 07_run_diagnostics.sh) ──
DIAG_OUTPUT_ROOT="${OUTPUT_ROOT}/diagnostics"
HELDOUT_DIAG_DIR="${DIAG_OUTPUT_ROOT}/heldout_4b_to_1p7b_300"
COMMON_CONTEXT="${HELDOUT_DIAG_DIR}/fixed_context/context_bank.parquet"
BASELINE_METRICS="${HELDOUT_DIAG_DIR}/fixed_context/theta0_metrics.parquet"

# ── Date tag for run directories ──────────────────────────────────────────
DATE_TAG="$(date +%Y%m%d)"

# ── Helper functions ──────────────────────────────────────────────────────

activate_env() {
  if [[ -f "${CONDA_SH}" ]]; then
    source "${CONDA_SH}"
    conda activate "${CONDA_ENV}"
  fi
}

get_pythonpath() {
  local active_sp
  active_sp="$(python3 -c 'import site; print(site.getsitepackages()[0])')"
  echo "${MEGATRON_LM_DIR}:${SLIME_DIR}:${active_sp}"
}

get_torch_cuda_lib() {
  python3 -c 'from pathlib import Path; import torch; sp = Path(torch.__file__).resolve().parents[1]; print(sp / "nvidia" / "cuda_runtime" / "lib")'
}

log() {
  echo "[$(date '+%F %T')] $*" | tee -a "${1:-/dev/stderr}"
}

# Compute port numbers for a lane and run index
# Usage: compute_ports LANE_PORT_BASE RUN_IDX
# Sets: TEACHER_PORT TEACHER_NCCL_PORT RAY_PORT RAY_DASHBOARD_PORT
#       RAY_OBJECT_PORT RAY_NODE_PORT RAY_AGENT_LISTEN RAY_AGENT_GRPC RAY_METRICS_PORT
compute_ports() {
  local base=$1 idx=$2
  TEACHER_PORT=$((14141 + base + idx))
  TEACHER_NCCL_PORT=$((24141 + base + idx))
  RAY_PORT=$((26379 + base + idx))
  RAY_DASHBOARD_PORT=$((8365 + base + idx))
  RAY_OBJECT_PORT=$((29076 + base + idx))
  RAY_NODE_PORT=$((29077 + base + idx))
  RAY_AGENT_LISTEN=$((29078 + base + idx))
  RAY_AGENT_GRPC=$((29079 + base + idx))
  RAY_METRICS_PORT=$((29080 + base + idx))
}

echo "=== TA-OPD 4B→1.7B Reproduction Config ==="
echo "PROJECT_ROOT = ${PROJECT_ROOT}"
echo "DATA_DIR     = ${DATA_DIR}"
echo "MODEL_DIR    = ${MODEL_DIR}"
echo "OUTPUT_ROOT  = ${OUTPUT_ROOT}"
echo "ALL_RUNS     = ${#ALL_RUNS[@]} (mask,ratio) combos × 3 seeds = $((${#ALL_RUNS[@]} * 3)) total"
