#!/usr/bin/env bash
# 修复 sgl_kernel import 失败
# 根因:
#   1. libnuma.so.1 缺失 (sm100/sm90 common_ops 都需要)
#   2. torch C++ libs (libtorch.so 等) 不在 LD_LIBRARY_PATH
# 用法: bash repro/fix_sgl_kernel.sh
set -eo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00_env.sh"
activate_env

echo "========================================="
echo " [1] 装 libnuma"
echo "========================================="
# 优先 conda-forge (无需 sudo); 失败则试 apt
if command -v conda >/dev/null 2>&1; then
  echo "尝试 conda install -c conda-forge libnuma..."
  conda install -c conda-forge -y libnuma || echo "(conda install 失败, 试 apt)"
fi

# 如果 conda 没装上, 试系统包
ENV_PREFIX="$(python3 -c 'import sys; print(sys.prefix)')"
if [[ ! -f "${ENV_PREFIX}/lib/libnuma.so.1" ]] && [[ ! -f "/usr/lib/x86_64-linux-gnu/libnuma.so.1" ]] && [[ ! -f "/lib/x86_64-linux-gnu/libnuma.so.1" ]]; then
  echo "libnuma 仍不在, 试 apt install libnuma1..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install -y libnuma1 || echo "  ⚠ apt install 失败 (可能需要 sudo 密码或无 root 权限)"
  fi
fi

# 确认
echo ""
echo "--- libnuma.so.1 在哪 ---"
for p in "${ENV_PREFIX}/lib" /usr/lib/x86_64-linux-gnu /lib/x86_64-linux-gnu /usr/local/lib; do
  if [[ -f "${p}/libnuma.so.1" ]]; then
    echo "  ✅ ${p}/libnuma.so.1"
  fi
done
echo ""

echo "========================================="
echo " [2] 把 torch/lib 加入 LD_LIBRARY_PATH 并固化"
echo "========================================="
TORCH_LIB="$(python3 -c 'from pathlib import Path; import torch; print(Path(torch.__file__).resolve().parent / "lib")')"
echo "torch/lib = ${TORCH_LIB}"
echo ""

# 当前 shell 立即生效
export LD_LIBRARY_PATH="${TORCH_LIB}:${ENV_PREFIX}/lib:${LD_LIBRARY_PATH:-}"

# 持久化: 写到 conda env 的 etc/conda/activate.d/ 脚本, 以后 conda activate 自动 export
ACTIVATE_D="${ENV_PREFIX}/etc/conda/activate.d"
mkdir -p "${ACTIVATE_D}"
cat > "${ACTIVATE_D}/sgl_kernel_env.sh" <<EOF
#!/usr/bin/env bash
# auto-generated by repro/fix_sgl_kernel.sh
export LD_LIBRARY_PATH="${TORCH_LIB}:${ENV_PREFIX}/lib:\${LD_LIBRARY_PATH:-}"
EOF
chmod +x "${ACTIVATE_D}/sgl_kernel_env.sh"
echo "  ✅ 已写 ${ACTIVATE_D}/sgl_kernel_env.sh (下次 conda activate 自动生效)"
echo ""

echo "========================================="
echo " [3] 验证 sgl_kernel import"
echo "========================================="
python3 -c "
import os
print('LD_LIBRARY_PATH:')
for p in os.environ.get('LD_LIBRARY_PATH', '').split(':'):
    if p: print(f'  {p}')
print()
try:
    import sgl_kernel
    print(f'✅ import sgl_kernel OK: {sgl_kernel.__file__}')
except Exception as e:
    print(f'❌ import sgl_kernel FAIL: {type(e).__name__}: {e}')
"
echo ""

echo "========================================="
echo " [4] 同步更新 repro/00_env.sh (可选)"
echo "========================================="
# 检查 00_env.sh 里 get_torch_cuda_lib 的 helper, 建议再加一个 get_torch_lib
if ! grep -q "get_torch_lib" "${SCRIPT_DIR}/00_env.sh"; then
  echo "  追加 get_torch_lib() helper 到 00_env.sh..."
  cat >> "${SCRIPT_DIR}/00_env.sh" <<'EOF'

get_torch_lib() {
  python3 -c 'from pathlib import Path; import torch; print(Path(torch.__file__).resolve().parent / "lib")'
}
EOF
  echo "  ✅ 已追加 (记得 git commit 一下)"
else
  echo "  已存在, 跳过"
fi
echo ""

echo "========================================="
echo " Done."
echo " 如果 [3] 显示 ✅, 继续: bash repro/run_all.sh 2"
echo "========================================="
